http_server:
  host: "0.0.0.0"
  port: "8073"
  timeout: 4s
  idle_timeout: 30s

proxy:
  timeout: 4s

database:
  user: postgres_user
  password: postgres_password
  database_name: proxy_db
  host: localhost
  port: 5432

logger:
  level: "info"